### ISSUE TITLE
krp: finalize site map

### ISSUE THREAD

**Issue by swcalise** [fillungo/client-KRP#1]
Homepage
Services
Work - All, Healthcare, Powersports, Philanthropy, Events, Sales&Fundraising, Video Ads
Pricing
About Us
Contact Us

**Comment by swcalise** [comment]
@Callus4815 we had a good meeting with John/Steve and are close to solidifying the site map/pages. We need to determine the best way to organize by both Industry and Video Types.

**Comment by Callus4815** [comment]
Check out the demo i have up. I added some videos. The videos wont play for
now due to a permissions on vimeo(expected behavior). Navigate to the Work
link and click on the Health,Philanthropic,Outreach sub menu. Its a start.
